compute_environment: LOCAL_MACHINE
deepspeed_config: null
fp16: true
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 1
mixed_precision: "fp16"  
use_cpu: false
offload_optimizer: true        # <<< envia otimizer states pra CPU
offload_parameters: true
distributed_type: NO
gradient_accumulation_steps: 4           # Acumula mais gradientes, reduzindo batch size efetivo
offload_optimizer_device: "cpu"          # Offload do otimizador para a CPU
offload_param_device: "cpu"              # Offload dos parâmetros para a CPU
